### PR TITLE
Initial commit for ngrok functionality

### PR DESCRIPTION
**Pull request by miike**
Draft PR as I haven't quite figured out how I'm doing the state handling wrong as I can start the tunnel but can't stop it correctly.

### CODE REVIEW

**Comment by jethron** [comment]
@miike try that version (I don't have ngrok set up to test myself).

**Comment by miike** [comment]
Thanks - that looks great. I'll finish preparing with the docs and we can prepare to release this week.

**Comment by jethron** [comment]
Works on my machine, permissions should work a bit better now, too.

Nice work!

**Review by jethron — APPROVED** [review]
LGTM

**Pull request merged**
